using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SeriusSoft.MtgDeckBuilder.Models.QueryHelpers
{
  public class SubCardTypes
  {
    public List<string> AllCardSubTypes
    {
      get
      {
        return new List<string>()
        {
          null,
          "Beast",
          "Juggernaut",
          "Wall",
          "Golem",
          "Aura",
          "Human Knight",
          "Wraith",
          "Demon",
          "Skeleton",
          "Shade",
          "Specter",
          "Spirit",
          "Imp",
          "Nightmare Horse",
          "Rat",
          "Human Assassin",
          "Zombie",
          "Vampire",
          "Skeleton Wall",
          "Elemental",
          "Shapeshifter",
          "Merfolk",
          "Djinn",
          "Illusion",
          "Human Pirate",
          "Human Wizard",
          "Serpent",
          "Bird",
          "Cockatrice",
          "Wurm",
          "Elf Archer",
          "Fungus Lizard",
          "Avatar",
          "Spider",
          "Bear",
          "Treefolk",
          "Human Druid",
          "Elf Druid",
          "Faerie",
          "Dryad",
          "Basilisk",
          "Wolf",
          "Plant Wall",
          "Elephant",
          "Dragon",
          "Dwarf",
          "Dwarf Warrior",
          "Goblin Warrior",
          "Goblin",
          "Gargoyle",
          "Ogre",
          "Giant",
          "Minotaur",
          "Orc",
          "Human Barbarian",
          "Orc Warrior",
          "Hydra",
          "Troll",
          "Human Soldier",
          "Pegasus",
          "Unicorn",
          "Avatar Incarnation",
          "Human Cleric",
          "Cat",
          "Angel",
          "Human",
          "Swamp",
          "Swamp Mountain",
          "Swamp Forest",
          "Mountain Plains",
          "Forest Plains",
          "Plains Swamp",
          "Mountain Forest",
          "Forest Island",
          "Plains Island",
          "Island Swamp",
          "Forest",
          "Mountain",
          "Island",
          "Plains",
          "Island Mountain",
          "Construct",
          "Human Warrior",
          "Efreet",
          "Devil",
          "Fish",
          "Turtle",
          "Snake",
          "Plant",
          "Human Rogue",
          "Human Bird",
          "Human Nomad",
          "Hound",
          "Ape",
          "Camel",
          "Desert",
          "Thopter",
          "Soldier",
          "Ouphe",
          "Human Artificer",
          "Atog",
          "Dwarf Artificer",
          "Goblin Artificer",
          "Urza's Mine",
          "Urza's Power",
          "Urza's Tower",
          "Horse",
          "Cleric",
          "Horror",
          "Insect",
          "Eye",
          "Slug",
          "Zombie Knight",
          "Gorgon",
          "Human Wolf",
          "Spirit Minion",
          "Fungus Demon",
          "Scorpion",
          "Nightstalker",
          "Bat",
          "Drake",
          "Hag",
          "Leviathan",
          "Cat Warrior",
          "Boar",
          "Elf",
          "Wombat",
          "Human Monk",
          "Satyr",
          "Wolverine",
          "Human Berserker",
          "Kobold",
          "Manticore",
          "Phoenix",
          "Kobold Soldier",
          "Yeti",
          "Ooze",
          "Gnome",
          "Ox",
          "Giant Soldier",
          "Kithkin",
          "Human Soldier Archer",
          "Dragon Wurm",
          "Giant Cleric",
          "Sphinx",
          "Elemental Spirit",
          "Elder Dragon",
          "Giant Warrior",
          "Zombie Wizard",
          "Human Archer",
          "Elf Warrior",
          "Human Advisor",
          "Human Shaman",
          "Insect Wizard",
          "Scarecrow",
          "Human Minion",
          "Merfolk Assassin",
          "Leech",
          "Goblin Wizard",
          "Thrull",
          "Cleric Knight",
          "Thrull Wizard",
          "Homarid",
          "Homarid Shaman",
          "Homarid Warrior",
          "Merfolk Cleric",
          "Merfolk Knight",
          "Merfolk Wizard",
          "Merfolk Soldier",
          "Elf Scout",
          "Fungus",
          "Human Cleric Druid",
          "Insect Monk Cleric",
          "Dwarf Soldier",
          "Goblin Shaman",
          "Orc Rogue",
          "Orgg",
          "Human Cleric Soldier",
          "Human Soldier Scout",
          "Human Cleric Knight",
          "Human Cleric Shaman",
          "Demon Minion",
          "Worm",
          "Illusion Wall",
          "Illusion Horse",
          "Kraken",
          "Human Wizard Artificer",
          "Aurochs",
          "Frog",
          "Elf Cleric Druid",
          "Lhurgoyf",
          "Lizard",
          "Giant Shaman",
          "Goblin Mutant",
          "Goat",
          "Orc Cleric",
          "Fox",
          "Elf Cleric",
          "Human Mercenary",
          "Centaur Archer",
          "Elemental Beast",
          "Rhino",
          "Hound Spirit",
          "Shade Knight",
          "Vampire Dwarf",
          "Oyster",
          "Whale",
          "Zombie Pirate",
          "Dwarf Wizard",
          "Ferret",
          "Badger",
          "Bear Spirit",
          "Faerie Druid",
          "Minotaur Spirit",
          "Minotaur Shaman",
          "Human Beast Soldier",
          "Horror Spirit",
          "Merfolk Scout",
          "Starfish",
          "Homarid Drone",
          "Elf Shaman",
          "Elf Spirit",
          "Ape Berserker",
          "Goblin Scout",
          "Ape Shaman",
          "Human Rogue Mercenary",
          "Angel Spirit",
          "Phelddagrif",
          "Human Cleric Wizard",
          "Dreadnought",
          "Shade Horror",
          "Demon Spirit",
          "Nightstalker Cat",
          "Crocodile",
          "Brushwagg",
          "Hyena",
          "Mongoose",
          "Fungus Wall",
          "Dwarf Nomad",
          "Cyclops",
          "Viashino Shaman",
          "Salamander",
          "Minotaur Berserker",
          "Viashino Warrior",
          "Griffin",
          "Human Scout",
          "Chimera",
          "Zombie Giant",
          "Cyclops Warrior",
          "Jellyfish",
          "Plant Fungus",
          "Antelope Beast",
          "Hippo",
          "Human Mercenary Knight",
          "Snake Assassin",
          "Snake Warrior",
          "Crocodile Skeleton",
          "Snake Skeleton",
          "Illusion Dragon",
          "Octopus",
          "Illusion Warrior",
          "Ape Warrior",
          "Plant Elemental",
          "Lizard Warrior",
          "Minotaur Warrior",
          "Goblin Berserker",
          "Elemental Horse",
          "Elf Soldier",
          "Human Monk Cleric",
          "Fungus Elemental",
          "Dwarf Berserker",
          "Dwarf Shaman",
          "Goblin Rogue",
          "Sliver",
          "Human Archer Minion",
          "Shade Spirit",
          "Dauthi Zombie",
          "Dauthi Horror",
          "Dauthi Minion",
          "Dauthi Knight Mercenary",
          "Dauthi Soldier",
          "Rabbit Beast",
          "Licid",
          "Minion",
          "Harpy Beast",
          "Squid Beast",
          "Crab",
          "Merfolk Shaman",
          "Thalakos Wizard",
          "Thalakos Illusion",
          "Thalakos Soldier",
          "Troll Giant",
          "Spike Drone",
          "Elemental Lizard",
          "Human Soldier Warrior",
          "Soltari Knight",
          "Soltari Soldier",
          "Soltari Monk Cleric",
          "Soltari Cleric",
          "Hellion Beast",
          "Kor Soldier",
          "Kor Nomad Soldier",
          "Kor Shaman Cleric",
          "Elf Druid Warrior",
          "Kor Spirit",
          "Spike",
          "Spike Soldier",
          "Zombie Assassin",
          "Giant Minion",
          "Merfolk Warrior",
          "Angel Warrior",
          "Kor Warrior Knight",
          "Centaur",
          "Viashino",
          "Bird Soldier",
          "Zombie Hound",
          "Chicken",
          "Clamfolk",
          "Worm Horror",
          "Merfolk Rogue",
          "Thalakos Soldier Scout",
          "Thalakos",
          "Kor Rogue Minion",
          "Dauthi Hound",
          "Vampire Hound",
          "Specter Spirit",
          "Goblin Assassin",
          "Ogre Shaman",
          "Elf Berserker",
          "Human Pirate Scout",
          "Human Pirate Warrior",
          "Human Pirate Wizard",
          "Ogre Berserker",
          "Ogre Warrior",
          "Zombie Minion",
          "Goblins",
          "Egg",
          "Elves",
          "Gus",
          "Human Cleric Minion",
          "Knight",
          "Lady of Proper Etiquette",
          "Cow",
          "Demon Beast",
          "Legend",
          "Human Soldier Rogue",
          "Human Mystic",
          "Human Barbarian Soldier",
          "Rabbit",
          "Human Soldier Assassin",
          "Scarecrow Soldier",
          "Zombie Cat",
          "Beeble",
          "Sponge",
          "Viashino Scout",
          "Carrier",
          "Kavu",
          "Elk Beast",
          "Masticore",
          "Metathran Soldier",
          "Goat Beast",
          "Cyclops Giant",
          "Bird Beast",
          "Elf Wizard",
          "Zombie Mercenary",
          "Human Spellshaper",
          "Human Rebel",
          "Human Rebel Warrior",
          "Dwarf Barbarian",
          "Merfolk Spellshaper",
          "Elf Spellshaper",
          "Horror Mercenary",
          "Lizard Mercenary",
          "Rhino Beast",
          "Ogre Rebel",
          "Cat Rebel",
          "Human Mercenary Assassin",
          "Human Spellshaper Assassin",
          "Dryad Spellshaper",
          "Unicorn Monger",
          "Human Monger",
          "Nautilus Beast",
          "Illusion Spirit",
          "Jellyfish Beast",
          "Boar Monger",
          "Harpy Mercenary",
          "Minotaur Monger",
          "Badger Beast",
          "Monger",
          "Satyr Beast",
          "Spellshaper",
          "Human Rebel Scout",
          "Zombie Dwarf",
          "Rebel Bird",
          "Human Soldier Knight",
          "Kor Rebel",
          "Bird Wizard",
          "Homunculus Illusion",
          "Plant Hound",
          "Beast Warrior",
          "Insect Worm",
          "Human Spellshaper Warrior",
          "Crab Beast",
          "Zombie Mercenary Assassin",
          "Metathran Zombie",
          "Metathran Wizard",
          "Metathran",
          "Elf Nomad",
          "Treefolk Cleric",
          "Elf Knight",
          "Merfolk Zombie",
          "Barbarian Zombie",
          "Elf Barbarian",
          "Human Cleric Archer",
          "Cat Soldier",
          "Cat Beast Warrior",
          "Kavu Scout",
          "Horse Rebel",
          "Human Rebel Mercenary",
          "Worm Mercenary",
          "Snake Wall",
          "Bird Mercenary",
          "Human Mercenary Rebel",
          "Horror Spellshaper",
          "Human Soldier Berserker",
          "Golem Warrior",
          "Human Nightmare Barbarian",
          "Minotaur Wizard",
          "Lair",
          "Volver",
          "Nightmare Drake",
          "Elf Druid Scout",
          "Human Flagbearer",
          "Anteater Beast",
          "Zombie Wurm",
          "Cat Spirit",
          "Zombie Frog Beast",
          "Zombie Centaur",
          "Human Barbarian Beast",
          "Cephalid Wizard",
          "Fungus Beast",
          "Merfolk Goblin",
          "Elf Merfolk",
          "Zombie Soldier Warrior",
          "Zombie Elf",
          "Goblin Soldier",
          "Zombie Snake",
          "Cephalid",
          "Zombie Druid",
          "Bird Soldier Archer",
          "Human Nomad Mystic",
          "Cephalid Wizard Scout",
          "Bird Soldier Wizard",
          "Elemental Bird",
          "Human Rat Minion",
          "Nightmare Horror",
          "Elemental Cat",
          "Elemental Ox Beast",
          "Insect Druid",
          "Elephant Wurm",
          "Human Bear Druid",
          "Centaur Horror",
          "Nightmare Beast",
          "Human Nomad Horror",
          "Cephalid Rogue",
          "Angel Horror",
          "Antelope",
          "Vampire Dragon",
          "Squirrel",
          "Centaur Druid",
          "Squirrel Beast",
          "Bird Soldier Horror",
          "Minotaur Scout",
          "Illusion Hound",
          "Human Barbarian Horror",
          "Centaur Druid Scout Archer",
          "Frog Beast",
          "Incarnation",
          "Human Nomad Cleric",
          "Centaur Shaman",
          "Zombie Imp",
          "Nightmare Salamander Beast",
          "Nightmare Fish Beast",
          "Zombie Scout",
          "Spirit Nomad",
          "Elemental Boar Beast",
          "Nightmare Crab",
          "Bird Soldier Spirit",
          "Nightmare Orgg",
          "Insect Spirit",
          "Nightmare Turtle Beast",
          "Insect Shade",
          "Nightmare Dragon",
          "Centaur Spirit",
          "Beast Mutant",
          "Human Wolf Minion",
          "Boar Beast",
          "Human Barbarian Warrior",
          "Cat Beast Spirit",
          "Bird Cleric",
          "Zombie Cleric",
          "Wizard Avatar",
          "Illusion Mutant",
          "Human Cleric Mercenary",
          "Elephant Cleric",
          "Lizard Beast",
          "Fish Beast",
          "Zombie Beast",
          "Cleric Avatar",
          "Elf Avatar",
          "Zombie Avatar",
          "Goblin Avatar",
          "Wolverine Beast",
          "Cat Giant",
          "Elf Wizard Shaman",
          "Zombie Goblin",
          "Zombie Bird",
          "Insect Beast",
          "Wizard",
          "Human Soldier Rebel",
          "Zombie Barbarian",
          "Zombie Dragon",
          "Illusion Sliver",
          "Bird Soldier Warrior",
          "Elf Mutant",
          "Zombie Insect",
          "Dragon Wizard",
          "Human Wizard Mutant",
          "Zombie Mutant",
          "Human Cleric Mutant",
          "Insect Druid Mutant",
          "Sliver Spirit",
          "Cat Beast",
          "Goblin Mercenary",
          "Cat Wizard",
          "Dragon Spirit",
          "Zombie Spirit",
          "Sliver Mutant",
          "Myr",
          "Zombie Lizard Beast",
          "Cat Knight",
          "Drone",
          "Equipment",
          "Slith",
          "Cat Cleric",
          "Elephant Soldier",
          "Troll Shaman",
          "Sheep",
          "Vedalken Wizard",
          "Human Barbarian Shaman",
          "Elemental Insect",
          "Slug Beast",
          "Golem Construct",
          "Vedalken Artificer",
          "Locus",
          "Troll Warrior",
          "Ouphe Rogue",
          "Zubera Spirit",
          "Rat Rogue",
          "Arcane",
          "Human Samurai",
          "Fox Cleric",
          "Moonfolk Rogue",
          "Snake Shaman",
          "Fox Wizard",
          "Fox Samurai",
          "Rat Samurai",
          "Human Rogue Rigger",
          "Zombie Crocodile",
          "Bringer",
          "Elf Warrior Scout",
          "Igpay",
          "Human Bureaucrat",
          "Elephant Rogue",
          "Goblin Waiter",
          "Orc Paratrooper",
          "Elf Rogue",
          "Elephant Townsfolk",
          "Demon Child",
          "Snake Warrior Archer",
          "Moonfolk Wizard",
          "Human Ninja",
          "Rat Ninja",
          "Ogre Samurai Mercenary",
          "Snake Shaman Scout",
          "Donkey Townsfolk",
          "Goblin Mime",
          "Donkey Shaman",
          "Ship",
          "Dinosaur",
          "Mummy",
          "Human Designer",
          "Donkey Lord",
          "Human Gamer",
          "Human Child",
          "Donkey Wizard",
          "Donkey Barbarian",
          "Zombie Gamer",
          "Human Hero",
          "Human Horror",
          "Donkey Zombie",
          "Kirin Spirit",
          "Rat Shaman",
          "Ogre Samurai Shaman",
          "Rat Warrior",
          "Human Samurai Archer",
          "Goblin Rogue Shaman",
          "Shrine",
          "Ogre Warrior Shaman",
          "Snake Monk",
          "Elemental Berserker",
          "Elf Warrior Druid",
          "Elemental Minion",
          "Insect Horror",
          "Elemental Horror",
          "Archon",
          "Ogre Rogue",
          "Plant Zombie",
          "Ogre Monk",
          "Moonfolk Monk",
          "Fox Monk",
          "Minotaur Soldier",
          "Faerie Rogue",
          "Camel Beast",
          "Dryad Shaman",
          "Zombie Drake",
          "Centaur Warrior",
          "Shapeshifter Spirit",
          "Skeleton Troll",
          "Plant Hydra",
          "Zombie Wolf",
          "Elemental Warrior",
          "Lammasu",
          "Centaur Berserker",
          "Elf Druid Archer",
          "Elephant Wizard",
          "Weird",
          "Viashino Berserker",
          "Vampire Skeleton",
          "Faerie Wizard",
          "Thrull Cleric",
          "Human Advisor Mutant",
          "Frog Mutant",
          "Snake Elf Druid",
          "Zombie Shaman",
          "Hellion Hydra",
          "Ogre Wizard",
          "Nephilim",
          "Troll Mutant",
          "Vedalken Knight",
          "Plant Mutant",
          "Elemental Mutant",
          "Faerie Scout",
          "Vedalken Wizard Mutant",
          "Elemental Scout",
          "Basilisk Mutant",
          "Ooze Mutant",
          "Human Mutant",
          "Spider Mutant",
          "Bird Rebel Soldier",
          "Insect Shaman",
          "Human Rebel Cleric",
          "Kithkin Rebel",
          "Kithkin Rebel Scout",
          "Goblin Advisor",
          "Assembly",
          "Urza's",
          "Orc Scout",
          "Zombie Fungus",
          "Dragon Avatar",
          "Wurm Spirit",
          "Fungus Sliver",
          "Kor Rebel Knight",
          "Human Rebel Knight",
          "Kor Rogue",
          "Spirit Bear",
          "Yeti Mutant",
          "Elemental Serpent",
          "Orc Shaman",
          "Spirit Soldier",
          "Troll Cleric",
          "Vampire Cat",
          "Ape Spirit",
          "Centaur Spellshaper",
          "Elemental Shapeshifter",
          "Worm Beast",
          "Zombie Cyclops",
          "Nomad Giant",
          "Zombie Warrior",
          "Fortification",
          "Hellion",
          "Spirit Spellshaper",
          "Human Rebel Rogue",
          "Faerie Spellshaper",
          "Kithkin Spellshaper",
          "Zombie Spellshaper",
          "Rebel Aura",
          "Elemental Spellshaper",
          "Kithkin Rogue",
          "Goblin Spellshaper",
          "Skeleton Wizard",
          "Imp Rebel",
          "Homunculus",
          "Human Rebel Assassin",
          "Elemental Shaman",
          "Kithkin Cleric",
          "Goblin Rigger",
          "Forest Dryad",
          "Kithkin Wizard",
          "Kithkin Knight",
          "Kithkin Soldier",
          "Merfolk Archer",
          "Treefolk Shaman",
          "Faerie Soldier",
          "Treefolk Warrior",
          "Treefolk Druid",
          "Kithkin Scout",
          "Treefolk Aura",
          "Elf Assassin",
          "Elemental Incarnation",
          "Chandra",
          "Kithkin Advisor",
          "Giant Wizard",
          "Garruk",
          "Liliana",
          "Jace",
          "Ajani",
          "Kithkin Archer",
          "Elemental Rogue",
          "Spirit Avatar",
          "Elemental Skeleton",
          "Giant Scout",
          "Elemental Knight",
          "Demon Hound",
          "Faerie Knight",
          "Bird Spirit",
          "Goblin Knight",
          "Zombie Rat",
          "Noggle Rogue",
          "Treefolk Horror",
          "Rogue",
          "Rogue Equipment",
          "Faerie Assassin",
          "Treefolk Assassin",
          "Shaman Equipment",
          "Soldier Equipment",
          "Goblin Warrior Shaman",
          "Kithkin Soldier Wizard",
          "Elemental Warrior Shaman",
          "Merfolk Rogue Warrior",
          "Spirit Giant",
          "Elf Warrior Shaman",
          "Giant Rogue",
          "Wizard Equipment",
          "Warrior Equipment",
          "Zombie Horror",
          "Hag Shaman",
          "Spirit Horror",
          "Rhino Soldier",
          "Noggle Wizard",
          "Hag Wizard",
          "Rhino Monk",
          "Elf Scout Ally",
          "Kor Scout",
          "Plant Elephant",
          "Ogre Mutant",
          "Elspeth",
          "Tezzeret",
          "Human Druid Warrior",
          "Hydra Beast",
          "Sarkhan",
          "Human Druid Shaman",
          "Viashino Skeleton",
          "Bird Skeleton",
          "Human Druid Wizard",
          "Human Druid Knight",
          "Zombie Ogre Warrior",
          "Vampire Shaman",
          "Rhino Monk Soldier",
          "Human Warrior Ally",
          "Bolas",
          "Hydra Avatar",
          "Bird Warrior",
          "Bird Scout",
          "Demon Illusion",
          "Bird Shaman",
          "Zombie Leech",
          "Human Cleric Ally",
          "Bird Ally",
          "Elf Archer Ally",
          "Surrakar",
          "Human Berserker Ally",
          "Vampire Rogue",
          "Vedalken Rogue",
          "Faerie Artificer",
          "Vedalken Zombie",
          "Zombie Lizard",
          "Cat Scout",
          "Vedalken Scout",
          "Vampire Warrior",
          "Demon Dragon",
          "Leviathan Horror",
          "Zombie Ogre",
          "Trap",
          "Rhino Warrior",
          "Viashino Soldier",
          "Spirit Wall",
          "Siren",
          "Fungus Snake",
          "Cat Ally",
          "Minotaur Warrior Ally",
          "Nissa",
          "Elemental Hound",
          "Human Soldier Ally",
          "Kor Cleric",
          "Kor Cleric Ally",
          "Gideon",
          "Elf Rogue Ally",
          "Goblin Warrior Ally",
          "Vampire Spirit",
          "Skeleton Wurm",
          "Eldrazi Drone",
          "Kor Monk",
          "Eldrazi",
          "Vampire Shade",
          "Eldrazi Aura",
          "Vampire Knight",
          "Kor Wizard",
          "Elemental Boar",
          "Vampire Assassin",
          "Zombie Berserker",
          "Elk",
          "Goblin Zombie",
          "Hippogriff",
          "Bird Horror",
          "Human Knight Ally",
          "Human Druid Ally",
          "Human Cleric Avatar",
          "Giant Druid",
          "Kor Knight",
          "Sorin",
          "Kor Soldier Ally",
          "Merfolk Wizard Ally",
          "Human Shaman Ally",
          "Human Wizard Ally",
          "Human Rogue Ally",
          "Ogre Shaman Ally",
          "Elf Druid Shaman",
          "Kor Artificer",
          "Shapeshifter Ally",
          "Elf Shaman Ally",
          "Goblin Artificer Ally",
          "Elemental Ox",
          "Illusion Beast",
          "Skeleton Warrior",
          "Vampire Wizard",
          "Elephant Monk",
          "Elf Artificer",
          "Berserker",
          "Warrior",
          "Shaman",
          "Saproling",
          "Myr Construct",
          "Koth",
          "Venser",
          "Dragon Skeleton",
          "Pest",
          "Giant Berserker",
          "Gremlin",
          "Praetor",
          "Karn",
          "Aura Curse",
          "Dragon Illusion",
          "Cat Monk",
          "Salamander Rogue",
          "Bear Illusion",
          "Spirit Knight",
          "Lizard Horror",
          "Spirit Bird",
          "Human Shaman Werewolf",
          "Werewolf",
          "Human Rogue Werewolf",
          "Human Werewolf",
          "Human Archer Werewolf",
          "Human Warrior Werewolf",
          "Human Advisor Werewolf",
          "Vampire Scout",
          "Human Insect",
          "Vampire Soldier",
          "Artificer",
          "Gorgon Wizard",
          "Zombie Elemental",
          "Minotaur Monk",
          "Fungus Shaman",
          "Tamiyo",
          "Wolf Warrior",
          "Spirit Wolf",
          "Spirit Treefolk",
          "Bat Skeleton",
          "Zombie Soldier",
          "Spirit Cleric",
          "Human Werewolf Shaman",
          "Zombie Troll",
          "Centaur Cleric",
          "Zombie Treefolk",
          "Angel Illusion",
          "Viashino Rogue",
          "Demon Ninja",
          "Gate",
          "Tibalt",
          "Vampire Archer",
          "Vedalken",
          "Dryad Soldier",
          "Vraska",
          "Spirit Advisor",
          "Elemental Soldier",
          "Fish Mutant",
          "Cyclops Soldier",
          "Lizard Drake",
          "Crocodile Frog",
          "Mutant Wizard",
          "Domri",
          "Bird Mutant",
          "Human Ooze",
          "Fish Crab",
          "Plant Skeleton",
          "Vedalken Soldier",
          "Human Insect Wizard",
          "Ral",
          "Human Merfolk",
          "Insect Warrior",
          "Weird Wizard",
          "Fish Illusion",
          "Sliver Construct",
          "Zombie Minotaur",
          "Rhino Cleric",
          "Ashiok",
          "Xenagos",
          "Satyr Druid",
          "Nymph Dryad",
          "God",
          "Satyr Shaman",
          "Centaur Advisor",
          "Centaur Wizard",
          "Skeleton Soldier",
          "Horse Fish",
          "Harpy",
          "Griffin Skeleton",
          "Nymph",
          "Satyr Rogue",
          "Sable",
          "Satyr Warrior",
          "Kiora",
          "Zombie Siren",
          "Nautilus",
          "Centaur Scout",
          "Zombie Satyr",
          "Satyr Soldier",
          "Lamia",
          "Siren Soldier"
        };
      }
    }
  }
}
